In [1]:
from scipy.stats import expon
from sklearn import svm
from sklearn.model_selection import RandomizedSearchCV
import pickle
import numpy as np
import geopandas as gpd
from geopandas import GeoDataFrame
import matplotlib
from matplotlib import pyplot

In [2]:
def train(X, Y):
    """
    Train classification algorithm.
    
    Train the Support Vector Machine classification algorithm using the
    specified fields. 

    Parameters
    ----------
    X: numpy 2D array
        A 2D numpy array where there is one row for each segment and each
        column represents an attribute of the segments. 

    Y: numpy 1D array
        A 1D numpy array equal in length to the number of records in segments.
        The single column contains actual class values for each of the
        segments.

    output_filename: string
        Output filename of the pickled trained SVM model.

    Returns
    -------
    model: svm.SVC
        Returns a trained SVM model that can be used to classify other data.

    """
    clf = svm.SVC()
        
    # specify parameters and distributions to sample from
    param_dist = {'C': expon(scale=100),
                  'gamma': expon(scale=.1),
                  'kernel': ['rbf'],
                  'class_weight':['balanced', None]}

    # run randomized search
    n_iter_search = 20
    random_search = RandomizedSearchCV(clf, param_distributions=param_dist,
                                   n_iter=n_iter_search)

    random_search.fit(X, Y) # this may take time...
    
    return random_search

In [3]:
def predict(model, X):
    """
    Classify segments using a trained SVM model

    Classify image segments using the trained Support Vector Machine model. 

    Parameters
    ----------
     model: svm.SVC
        A trained SVM model that can be used to classify other data.

    X: numpy 2D array
        A 2D numpy array where there is one row for each segment and each
        column represents an attribute of the segments. Identical to segments
        from the train_classifier function.
    """
    predictions = model.predict(X)

    return predictions

In [26]:
for_training = gpd.read_file("ClassifiedChevelon.gpkg")

In [27]:
for_training.head

<bound method NDFrame.head of        blue_min  blue_max    blue_mean    blue_std  green_min  green_max  \
0         959.0     959.0   959.000000    0.000000     1227.0     1227.0
1        1094.0    1094.0  1094.000000    0.000000     1393.0     1393.0
2         866.0     866.0   866.000000    0.000000     1093.0     1093.0
3        1162.0    1162.0  1162.000000    0.000000     1459.0     1459.0
4         929.0    1169.0  1028.333333   94.270297     1206.0     1444.0
...         ...       ...          ...         ...        ...        ...
36799    1117.0    1419.0  1245.955056   68.133529     1395.0     1705.0
36800       0.0    1274.0   373.324461  455.137399        0.0     1495.0
36801       0.0    1552.0     1.712042   40.834082        0.0     1839.0
36802       0.0    1465.0  1137.597938  487.652628        0.0     1717.0
36803    1215.0    1406.0  1311.653061   40.608535     1502.0     1633.0

        green_mean   green_std  red_min  red_max  ...  minor_axis_length  \
0      1227.000000    0.000000   1545.0   1545.0  ...           7.895067
1      1393.000000    0.000000   1786.0   1786.0  ...           0.000000
2      1093.000000    0.000000   1415.0   1415.0  ...           0.000000
3      1459.000000    0.000000   1860.0   1860.0  ...           0.000000
4      1300.666667   89.240624   1541.0   1832.0  ...           1.987500
...            ...         ...      ...      ...  ...                ...
36799  1515.786517   79.911534   1731.0   2148.0  ...          10.018145
36800   475.223067  576.771350      0.0   1804.0  ...          12.789344
36801     2.179134   51.806896      0.0   2367.0  ...        1329.730832
36802  1372.958763  588.135354      0.0   2199.0  ...           7.293640
36803  1571.311224   31.406974   1787.0   1993.0  ...          14.618240

       orientation  sobel_min  sobel_max  sobel_mean  sobel_std     dn  Class  \
0         1.197769   0.000000   0.000000    0.000000   0.000000      8    2.0
1        -0.785398   0.000000   0.000000    0.000000   0.000000      5    NaN
2         0.785398   0.000000   0.000000    0.000000   0.000000      4    3.0
3        -0.785398   0.000000   0.000000    0.000000   0.000000      5    NaN
4        -0.673043   0.000000   0.000000    0.000000   0.000000      7    3.0
...            ...        ...        ...         ...        ...    ...    ...
36799     1.167805   0.000271   0.002755    0.001261   0.000520  26900    NaN
36800     1.331593   0.000027   0.005197    0.001591   0.000921  25896    NaN
36801     1.095076   0.000000   0.018006    0.001011   0.000806  26688    NaN
36802     0.065029   0.000326   0.003970    0.001660   0.000827  26917    NaN
36803    -0.089838   0.000171   0.003474    0.001531   0.000624  26906    NaN

           ndvi                                           geometry
0      0.247443  POLYGON ((519804 3830847, 519804 3830844, 5198...
1      0.201431  POLYGON ((519819 3830844, 519819 3830841, 5198...
2      0.241897  POLYGON ((519783 3830841, 519783 3830838, 5197...
3      0.199139  POLYGON ((519822 3830841, 519822 3830838, 5198...
4      0.228707  POLYGON ((519825 3830838, 519825 3830829, 5198...
...         ...                                                ...
36799  0.189358  POLYGON ((516561 3823425, 516561 3823422, 5165...
36800  0.281338  POLYGON ((517626 3823764, 517626 3823752, 5176...
36801  0.261935  POLYGON ((521448 3830424, 521448 3830406, 5214...
36802  0.191823  POLYGON ((516597 3823386, 516597 3823383, 5165...
36803  0.188571  POLYGON ((516594 3823410, 516594 3823404, 5165...

[36804 rows x 31 columns]>

In [28]:
big_train = for_training[~np.isnan(for_training["Class"])]

In [29]:
# big_train = for_training[for_training["Class"]!=np.isnan]

In [30]:
big_train.head

<bound method NDFrame.head of        blue_min  blue_max    blue_mean    blue_std  green_min  green_max  \
0         959.0     959.0   959.000000    0.000000     1227.0     1227.0
2         866.0     866.0   866.000000    0.000000     1093.0     1093.0
4         929.0    1169.0  1028.333333   94.270297     1206.0     1444.0
6         963.0     963.0   963.000000    0.000000     1213.0     1213.0
9         911.0     911.0   911.000000    0.000000     1190.0     1190.0
...         ...       ...          ...         ...        ...        ...
31776     829.0     920.0   861.133333   23.996852     1041.0     1113.0
32382     865.0     892.0   878.500000   13.500000     1133.0     1143.0
32872     608.0    1023.0   797.985714   72.170597      817.0     1204.0
35294     757.0    1241.0  1038.830986  114.101510      989.0     1498.0
36687     417.0     472.0   448.333333   23.098822      606.0      658.0

        green_mean   green_std  red_min  red_max  ...  minor_axis_length  \
0      1227.000000    0.000000   1545.0   1545.0  ...           7.895067
2      1093.000000    0.000000   1415.0   1415.0  ...           0.000000
4      1300.666667   89.240624   1541.0   1832.0  ...           1.987500
6      1213.000000    0.000000   1550.0   1550.0  ...           1.987500
9      1190.000000    0.000000   1511.0   1511.0  ...           0.000000
...            ...         ...      ...      ...  ...                ...
31776  1079.533333   22.198699   1282.0   1361.0  ...           1.382516
32382  1138.000000    5.000000   1353.0   1397.0  ...           0.000000
32872  1018.547619   71.187680    982.0   1480.0  ...          14.062714
35294  1278.690141  122.358581   1147.0   1821.0  ...           6.083229
36687   630.000000   21.416505    682.0    745.0  ...          36.354741

       orientation  sobel_min  sobel_max  sobel_mean  sobel_std     dn  Class  \
0         1.197769   0.000000   0.000000    0.000000   0.000000      8    2.0
2         0.785398   0.000000   0.000000    0.000000   0.000000      4    3.0
4        -0.673043   0.000000   0.000000    0.000000   0.000000      7    3.0
6        -0.673043   0.000000   0.000000    0.000000   0.000000      7    2.0
9        -0.785398   0.000000   0.000000    0.000000   0.000000     12    2.0
...            ...        ...        ...         ...        ...    ...    ...
31776    -0.056247   0.000261   0.001634    0.000762   0.000386  23295    2.0
32382     0.000000   0.001182   0.002085    0.001634   0.000451  23783    2.0
32872     1.153051   0.000046   0.002842    0.001018   0.000562  23833    2.0
35294     1.360472   0.000161   0.003365    0.001235   0.000708  25698    3.0
36687    -0.368318   0.000400   0.001804    0.001084   0.000574  26695    1.0

           ndvi                                           geometry
0      0.247443  POLYGON ((519804 3830847, 519804 3830844, 5198...
2      0.241897  POLYGON ((519783 3830841, 519783 3830838, 5197...
4      0.228707  POLYGON ((519825 3830838, 519825 3830829, 5198...
6      0.246109  POLYGON ((519834 3830829, 519834 3830826, 5198...
9      0.242417  POLYGON ((519837 3830823, 519837 3830820, 5198...
...         ...                                                ...
31776  0.291830  POLYGON ((518424 3824253, 518424 3824250, 5184...
32382  0.247297  POLYGON ((518547 3824184, 518547 3824181, 5185...
32872  0.291877  POLYGON ((518442 3824190, 518442 3824181, 5184...
35294  0.247389  POLYGON ((517629 3823788, 517629 3823785, 5176...
36687  0.571055  POLYGON ((517326 3823479, 517326 3823473, 5173...

[173 rows x 31 columns]>

In [31]:
big_train.columns.values

array(['blue_min', 'blue_max', 'blue_mean', 'blue_std', 'green_min',
       'green_max', 'green_mean', 'green_std', 'red_min', 'red_max',
       'red_mean', 'red_std', 'nir_min', 'nir_max', 'nir_mean', 'nir_std',
       'area', 'perimeter', 'eccentricity', 'equivalent_diameter',
       'major_axis_length', 'minor_axis_length', 'orientation',
       'sobel_min', 'sobel_max', 'sobel_mean', 'sobel_std', 'dn', 'Class',
       'ndvi', 'geometry'], dtype=object)

In [32]:
labels = big_train['Class']

In [33]:
labels

0        2.0
2        3.0
4        3.0
6        2.0
9        2.0
        ...
31776    2.0
32382    2.0
32872    2.0
35294    3.0
36687    1.0
Name: Class, Length: 173, dtype: float64

In [34]:
classes = big_train[['red_mean', 'green_mean', "blue_mean", "nir_mean", "eccentricity", "orientation", "sobel_max"]]

In [35]:
classes

,red_mean,green_mean,blue_mean,nir_mean,eccentricity,orientation,sobel_max
0,1545.000000,1227.000000,959.000000,2561.000000,0.789692,1.197769,0.000000
2,1415.000000,1093.000000,866.000000,2318.000000,0.000000,0.785398,0.000000
4,1664.000000,1300.666667,1028.333333,2650.833333,0.925104,-0.673043,0.000000
6,1550.000000,1213.000000,963.000000,2562.000000,0.925104,-0.673043,0.000000
9,1511.000000,1190.000000,911.000000,2478.000000,1.000000,-0.785398,0.000000
11,1221.767857,1003.910714,756.107143,2143.625000,0.956790,0.914942,0.000000
13,1647.000000,1309.000000,1010.000000,2527.000000,0.489054,-1.386899,0.000000
15,1679.500000,1320.500000,1023.000000,2623.500000,1.000000,0.000000,0.000000
18,1506.152174,1196.369565,945.652174,2461.086957,0.875389,0.301837,0.000000
23,1661.150000,1324.375000,1038.100000,2605.425000,0.902664,0.919684,0.000000
29,1857.000000,1487.000000,1234.000000,2808.000000,1.000000,0.785398,0.000000
33,1849.882353,1527.333333,1230.137255,2877.745098,0.802558,-1.190525,0.000000
36,1844.750000,1512.750000,1181.750000,3032.000000,1.000000,-1.570796,0.000000
39,1719.258621,1361.034483,1071.844828,2651.862069,0.623283,0.694458,0.000000
43,1324.265060,1083.481928,859.566265,2211.120482,0.830469,-0.980366,0.000000
47,1403.500000,1138.500000,831.000000,2538.500000,0.873774,1.312913,0.000000
50,1568.000000,1279.000000,1034.000000,2507.000000,1.000000,-0.785398,0.000000
52,1958.666667,1518.000000,1214.000000,2831.333333,0.955342,-0.184674,0.000000
55,1657.454545,1309.318182,1029.363636,2603.545455,0.693591,1.463043,0.000000
58,1672.000000,1298.000000,937.000000,2693.000000,0.965547,-1.122769,0.000000
61,1759.505618,1444.910112,1164.786517,2708.359551,0.876030,1.029046,0.000000
64,1425.298246,1163.596491,908.964912,2341.596491,0.570759,-1.126672,0.000000
67,1564.030303,1219.606061,922.818182,2619.272727,0.952094,-0.211414,0.000000
70,1433.187500,1150.041667,881.138889,2434.895833,0.667228,-0.023294,0.000000
85,1776.000000,1397.500000,1089.500000,2776.500000,1.000000,0.000000,0.000000
94,1800.500000,1396.500000,1117.000000,2783.500000,1.000000,0.000000,0.000000
106,1778.186047,1371.418605,1035.255814,3438.511628,0.976194,1.566969,0.000000
108,1729.608696,1397.782609,1099.173913,2677.565217,0.953337,-1.460734,0.000000
114,1827.928571,1455.714286,1148.857143,2827.642857,0.836977,-0.612129,0.000000
120,2034.444444,1593.666667,1284.666667,3069.333333,0.735031,0.803908,0.000000
...,...,...,...,...,...,...,...
8533,1138.642857,917.285714,700.285714,2548.166667,0.808795,-1.010534,0.001178
9086,2129.364583,1749.291667,1435.770833,3143.708333,0.646672,-1.058821,0.001442
9984,1035.625000,843.025000,623.100000,2006.025000,0.835283,0.868587,0.002700
11528,1424.750000,1166.833333,915.993056,2387.395833,0.935755,0.247380,0.001212
11532,1622.500000,1317.000000,1032.500000,2642.000000,0.862277,0.342488,0.000541
11546,2023.000000,1607.000000,1330.000000,3000.000000,1.000000,-0.785398,0.000892
11909,883.000000,774.000000,494.000000,3101.000000,0.622481,1.213417,0.000877
13406,1375.681818,1087.045455,804.772727,2509.681818,0.919527,1.091259,0.001598
14472,805.294118,676.823529,444.764706,2985.941176,0.738178,1.422636,0.002224
14646,0.000000,0.000000,0.000000,0.000000,1.000000,-0.785398,0.000776
17136,1400.333333,1179.166667,901.666667,2554.333333,0.806458,-0.843214,0.000739
18200,2339.000000,1871.000000,1507.000000,3456.000000,0.000000,0.785398,0.001135
20483,1266.880000,1060.800000,805.360000,2453.400000,0.956177,0.961156,0.001973
21247,0.000000,0.000000,0.000000,0.000000,0.856011,1.095076,0.000325
21511,1130.000000,975.000000,717.000000,2680.000000,1.000000,0.785398,0.000095
24000,1664.090909,1373.000000,1100.454545,2757.848485,0.931869,0.049294,0.002188
24177,1119.000000,916.000000,662.000000,2505.000000,1.000000,0.785398,0.000401
24686,1665.402299,1405.011494,1137.494253,2759.781609,0.702469,0.081475,0.002554
25453,1045.000000,922.000000,658.777778,3729.666667,0.893557,0.733412,0.001547
26639,1204.176471,971.000000,733.705882,2860.882353,0.950465,0.969452,0.001299
26720,862.600000,748.600000,485.400000,3188.200000,0.906275,-0.343836,0.001681
29648,1338.000000,1123.000000,841.000000,2478.000000,1.000000,-0.785398,0.001106
29822,841.000000,744.000000,553.000000,3212.000000,0.919460,1.223427,0.002005
29925,844.000000,768.000000,561.000000,3194.000000,0.986861,-1.425068,0.000823
31024,693.611111,635.925926,447.703704,2679.694444,0.703923,1.538464,0.002190
31776,1321.800000,1079.533333,861.133333,2411.200000,0.995376,-0.056247,0.001634
32382,1375.000000,1138.000000,878.500000,2278.500000,1.000000,0.000000,0.002085
32872,1228.333333,1018.547619,797.985714,2240.933333,0.850192,1.153051,0.002842
35294,1516.760563,1278.690141,1038.830986,2513.901408,0.938356,1.360472,0.003365
36687,710.333333,630.000000,448.333333,2601.666667,0.957281,-0.368318,0.001804

In [36]:
type(classes)

pandas.core.frame.DataFrame

In [37]:
type(labels)

pandas.core.series.Series

In [38]:
labels

0        2.0
2        3.0
4        3.0
6        2.0
9        2.0
        ...
31776    2.0
32382    2.0
32872    2.0
35294    3.0
36687    1.0
Name: Class, Length: 173, dtype: float64

In [39]:
model = train(classes, labels)

/opt/conda/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)

In [40]:
to_predict = for_training[['red_mean', 'green_mean', "blue_mean", "nir_mean", "eccentricity", "orientation", "sobel_max"]]

In [41]:
output = predict(model, to_predict.values)

In [42]:
output

array([2., 2., 3., ..., 3., 2., 3.])

In [43]:
for_training['classified'] = output

In [44]:
for_training

,blue_min,blue_max,blue_mean,blue_std,green_min,green_max,green_mean,green_std,red_min,red_max,...,orientation,sobel_min,sobel_max,sobel_mean,sobel_std,dn,Class,ndvi,geometry,classified
0,959.0,959.0,959.000000,0.000000,1227.0,1227.0,1227.000000,0.000000,1545.0,1545.0,...,1.197769,0.000000,0.000000,0.000000,0.000000e+00,8,2.0,0.247443,"POLYGON ((519804 3830847, 519804 3830844, 5198...",2.0
1,1094.0,1094.0,1094.000000,0.000000,1393.0,1393.0,1393.000000,0.000000,1786.0,1786.0,...,-0.785398,0.000000,0.000000,0.000000,0.000000e+00,5,NaN,0.201431,"POLYGON ((519819 3830844, 519819 3830841, 5198...",2.0
2,866.0,866.0,866.000000,0.000000,1093.0,1093.0,1093.000000,0.000000,1415.0,1415.0,...,0.785398,0.000000,0.000000,0.000000,0.000000e+00,4,3.0,0.241897,"POLYGON ((519783 3830841, 519783 3830838, 5197...",3.0
3,1162.0,1162.0,1162.000000,0.000000,1459.0,1459.0,1459.000000,0.000000,1860.0,1860.0,...,-0.785398,0.000000,0.000000,0.000000,0.000000e+00,5,NaN,0.199139,"POLYGON ((519822 3830841, 519822 3830838, 5198...",2.0
4,929.0,1169.0,1028.333333,94.270297,1206.0,1444.0,1300.666667,89.240624,1541.0,1832.0,...,-0.673043,0.000000,0.000000,0.000000,0.000000e+00,7,3.0,0.228707,"POLYGON ((519825 3830838, 519825 3830829, 5198...",3.0
5,763.0,903.0,840.333333,35.166515,1032.0,1131.0,1094.179487,23.650090,1298.0,1416.0,...,-0.419124,0.000000,0.000000,0.000000,0.000000e+00,2,NaN,0.256126,"POLYGON ((519774 3830844, 519774 3830838, 5197...",3.0
6,963.0,963.0,963.000000,0.000000,1213.0,1213.0,1213.000000,0.000000,1550.0,1550.0,...,-0.673043,0.000000,0.000000,0.000000,0.000000e+00,7,2.0,0.246109,"POLYGON ((519834 3830829, 519834 3830826, 5198...",2.0
7,793.0,976.0,893.627451,44.732302,1059.0,1227.0,1157.725490,35.170218,1363.0,1544.0,...,0.333665,0.000000,0.000000,0.000000,0.000000e+00,3,NaN,0.239773,"POLYGON ((519789 3830844, 519789 3830838, 5197...",2.0
8,830.0,980.0,905.615385,46.906681,1092.0,1268.0,1166.076923,54.644954,1397.0,1574.0,...,-0.793528,0.000000,0.000000,0.000000,0.000000e+00,9,NaN,0.255844,"POLYGON ((519828 3830826, 519828 3830820, 5198...",2.0
9,911.0,911.0,911.000000,0.000000,1190.0,1190.0,1190.000000,0.000000,1511.0,1511.0,...,-0.785398,0.000000,0.000000,0.000000,0.000000e+00,12,2.0,0.242417,"POLYGON ((519837 3830823, 519837 3830820, 5198...",2.0
10,726.0,1361.0,1145.975610,179.918069,1015.0,1666.0,1457.756098,192.724849,1263.0,2056.0,...,0.350082,0.000000,0.000000,0.000000,0.000000e+00,10,NaN,0.215976,"POLYGON ((519678 3830829, 519678 3830826, 5196...",2.0
11,648.0,936.0,756.107143,59.459974,896.0,1140.0,1003.910714,56.574627,1088.0,1401.0,...,0.914942,0.000000,0.000000,0.000000,0.000000e+00,39,2.0,0.273923,"POLYGON ((519705 3830835, 519705 3830832, 5197...",2.0
12,993.0,993.0,993.000000,0.000000,1283.0,1283.0,1283.000000,0.000000,1614.0,1614.0,...,-0.785398,0.000000,0.000000,0.000000,0.000000e+00,12,NaN,0.211722,"POLYGON ((519840 3830820, 519840 3830817, 5198...",2.0
13,1010.0,1010.0,1010.000000,0.000000,1309.0,1309.0,1309.000000,0.000000,1647.0,1647.0,...,-1.386899,0.000000,0.000000,0.000000,0.000000e+00,23,2.0,0.210829,"POLYGON ((519843 3830817, 519843 3830814, 5198...",2.0
14,858.0,1033.0,950.416667,42.263969,1148.0,1298.0,1229.583333,37.124247,1478.0,1646.0,...,1.197769,0.000000,0.000000,0.000000,0.000000e+00,8,NaN,0.234606,"POLYGON ((519807 3830844, 519807 3830841, 5198...",2.0
15,995.0,1051.0,1023.000000,28.000000,1291.0,1350.0,1320.500000,29.500000,1632.0,1727.0,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,15,2.0,0.219382,"POLYGON ((519843 3830814, 519843 3830811, 5198...",2.0
16,1160.0,1160.0,1160.000000,0.000000,1456.0,1456.0,1456.000000,0.000000,1805.0,1805.0,...,1.102362,0.000000,0.000000,0.000000,0.000000e+00,17,NaN,0.203442,"POLYGON ((519612 3830811, 519612 3830808, 5196...",3.0
17,784.0,1233.0,989.834395,89.859682,1053.0,1455.0,1250.095541,78.378372,1300.0,1806.0,...,0.905806,0.000000,0.000000,0.000000,0.000000e+00,1,NaN,0.227109,"POLYGON ((519759 3830850, 519759 3830847, 5197...",2.0
18,834.0,1111.0,945.652174,52.484870,1052.0,1393.0,1196.369565,62.392293,1337.0,1705.0,...,0.301837,0.000000,0.000000,0.000000,0.000000e+00,13,2.0,0.240705,"POLYGON ((519768 3830820, 519768 3830808, 5197...",2.0
19,796.0,1221.0,996.678571,133.408089,1072.0,1552.0,1296.928571,146.814491,1274.0,1882.0,...,1.084137,0.000000,0.000000,0.000000,0.000000e+00,14,NaN,0.236244,"POLYGON ((519672 3830820, 519672 3830817, 5196...",2.0
20,1015.0,1177.0,1085.307692,56.022502,1306.0,1439.0,1368.230769,47.989027,1594.0,1794.0,...,1.204885,0.000000,0.000000,0.000000,0.000000e+00,20,NaN,0.222226,"POLYGON ((519756 3830817, 519756 3830808, 5197...",2.0
21,847.0,1166.0,997.035971,70.402176,1117.0,1415.0,1261.129496,63.348168,1425.0,1826.0,...,-1.386899,0.000000,0.000000,0.000000,0.000000e+00,23,NaN,0.231587,"POLYGON ((519816 3830847, 519816 3830835, 5198...",2.0
22,976.0,976.0,976.000000,0.000000,1268.0,1268.0,1268.000000,0.000000,1555.0,1555.0,...,0.785398,0.000000,0.000000,0.000000,0.000000e+00,21,NaN,0.240908,"POLYGON ((519762 3830805, 519762 3830802, 5197...",2.0
23,939.0,1135.0,1038.100000,56.281791,1218.0,1437.0,1324.375000,55.976641,1550.0,1820.0,...,0.919684,0.000000,0.000000,0.000000,0.000000e+00,11,2.0,0.221319,"POLYGON ((519756 3830823, 519756 3830820, 5197...",2.0
24,947.0,947.0,947.000000,0.000000,1225.0,1225.0,1225.000000,0.000000,1457.0,1457.0,...,0.785398,0.000000,0.000000,0.000000,0.000000e+00,21,NaN,0.269857,"POLYGON ((519759 3830802, 519759 3830799, 5197...",2.0
25,737.0,1049.0,852.146341,70.755009,1004.0,1242.0,1103.975610,70.842487,1289.0,1537.0,...,0.416555,0.000000,0.000000,0.000000,0.000000e+00,22,NaN,0.265882,"POLYGON ((519783 3830811, 519783 3830808, 5197...",2.0
26,891.0,1330.0,1087.619048,135.487998,1188.0,1569.0,1361.619048,122.685225,1444.0,1882.0,...,1.102362,0.000000,0.000000,0.000000,0.000000e+00,17,NaN,0.220882,"POLYGON ((519606 3830808, 519606 3830805, 5196...",2.0
27,766.0,766.0,766.000000,0.000000,1053.0,1053.0,1053.000000,0.000000,1291.0,1291.0,...,1.095648,0.000000,0.000000,0.000000,0.000000e+00,27,NaN,0.282379,"POLYGON ((519669 3830796, 519669 3830793, 5196...",2.0
28,1176.0,1225.0,1200.500000,24.500000,1464.0,1512.0,1488.000000,24.000000,1757.0,1854.0,...,0.000000,0.000000,0.000000,0.000000,0.000000e+00,26,NaN,0.255924,"POLYGON ((519630 3830793, 519630 3830790, 5196...",2.0
29,1234.0,1234.0,1234.000000,0.000000,1487.0,1487.0,1487.000000,0.000000,1857.0,1857.0,...,0.785398,0.000000,0.000000,0.000000,0.000000e+00,29,2.0,0.203859,"POLYGON ((519660 3830793, 519660 3830790, 5196...",2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36774,700.0,700.0,700.000000,0.000000,920.0,920.0,920.000000,0.000000,1026.0,1026.0,...,0.318659,0.000671,0.000671,0.000671,0.000000e+00,26904,NaN,0.318046,"POLYGON ((517473 3823410, 517473 3823407, 5174...",2.0
36775,1055.0,1100.0,1077.500000,22.500000,1299.0,1352.0,1325.500000,26.500000,1540.0,1583.0,...,1.079399,0.001568,0.001569,0.001569,6.330685e-07,26905,NaN,0.257048,"POLYGON ((516525 3823407, 516525 3823401, 5165...",2.0
36776,615.0,701.0,662.000000,30.361159,817.0,905.0,861.700000,29.175503,940.0,1026.0,...,0.318659,0.000058,0.001852,0.001045,6.095518e-04,26904,NaN,0.316792,"POLYGON ((517464 3823410, 517464 3823407, 5174...",2.0
36777,612.0,830.0,714.607143,49.066771,818.0,1057.0,929.785714,57.187260,994.0,1248.0,...,1.110103,0.000028,0.002814,0.001161,6.393087e-04,26898,NaN,0.325675,"POLYGON ((516450 3823431, 516450 3823419, 5164...",2.0
36778,1037.0,1037.0,1037.000000,0.000000,1304.0,1304.0,1304.000000,0.000000,1503.0,1503.0,...,1.079399,0.001132,0.001132,0.001132,0.000000e+00,26905,NaN,0.275313,"POLYGON ((516522 3823401, 516522 3823398, 5165...",2.0
36779,1210.0,1232.0,1221.000000,11.000000,1477.0,1499.0,1488.000000,11.000000,1857.0,1879.0,...,-0.392699,0.000368,0.001815,0.001091,7.236199e-04,26908,NaN,0.196040,"POLYGON ((516552 3823401, 516552 3823398, 5165...",2.0
36780,872.0,902.0,880.750000,12.356678,1113.0,1123.0,1118.250000,3.960745,1333.0,1353.0,...,0.553574,0.000908,0.003025,0.002168,8.485867e-04,26907,NaN,0.297601,"POLYGON ((516477 3823401, 516477 3823398, 5164...",2.0
36781,1063.0,1063.0,1063.000000,0.000000,1328.0,1328.0,1328.000000,0.000000,1564.0,1564.0,...,0.785398,0.001923,0.001923,0.001923,0.000000e+00,26912,NaN,0.266072,"POLYGON ((516519 3823398, 516519 3823395, 5165...",2.0
36782,1177.0,1214.0,1195.500000,18.500000,1461.0,1482.0,1471.500000,10.500000,1830.0,1877.0,...,-0.392699,0.001231,0.001421,0.001326,9.468526e-05,26908,NaN,0.202796,"POLYGON ((516558 3823398, 516558 3823395, 5165...",2.0
36783,1345.0,1365.0,1355.000000,10.000000,1565.0,1586.0,1575.500000,10.500000,1920.0,1964.0,...,0.000000,0.000900,0.002202,0.001551,6.505880e-04,26909,NaN,0.180591,"POLYGON ((516576 3823398, 516576 3823395, 5165...",3.0
36784,909.0,909.0,909.000000,0.000000,1145.0,1145.0,1145.000000,0.000000,1396.0,1396.0,...,0.785398,0.001508,0.001508,0.001508,0.000000e+00,26911,NaN,0.275370,"POLYGON ((516474 3823395, 516474 3823392, 5164...",2.0
36785,702.0,946.0,833.555556,54.172499,936.0,1148.0,1063.730159,50.709320,1131.0,1400.0,...,0.462186,0.000111,0.002710,0.001240,6.482339e-04,26896,NaN,0.301243,"POLYGON ((516477 3823419, 516477 3823416, 5164...",2.0
36786,1122.0,1122.0,1122.000000,0.000000,1366.0,1366.0,1366.000000,0.000000,1632.0,1632.0,...,0.785398,0.001465,0.001465,0.001465,0.000000e+00,26912,NaN,0.260032,"POLYGON ((516516 3823395, 516516 3823392, 5165...",3.0
36787,1298.0,1298.0,1298.000000,0.000000,1572.0,1572.0,1572.000000,0.000000,1932.0,1932.0,...,0.785398,0.002602,0.002602,0.002602,0.000000e+00,26914,NaN,0.206734,"POLYGON ((516528 3823395, 516528 3823392, 5165...",2.0
36788,1180.0,1180.0,1180.000000,0.000000,1410.0,1410.0,1410.000000,0.000000,1656.0,1656.0,...,0.785398,0.001415,0.001415,0.001415,0.000000e+00,26915,NaN,0.266120,"POLYGON ((516513 3823392, 516513 3823389, 5165...",2.0
36789,1332.0,1332.0,1332.000000,0.000000,1595.0,1595.0,1595.000000,0.000000,1946.0,1946.0,...,0.785398,0.002118,0.002118,0.002118,0.000000e+00,26914,NaN,0.217216,"POLYGON ((516525 3823392, 516525 3823389, 5165...",3.0
36790,893.0,928.0,908.750000,12.813567,1105.0,1125.0,1113.750000,7.595229,1287.0,1319.0,...,0.553574,0.000352,0.002483,0.001296,7.718682e-04,26913,NaN,0.267224,"POLYGON ((517494 3823395, 517494 3823392, 5174...",2.0
36791,0.0,1078.0,475.480616,318.310071,0.0,1382.0,623.770579,410.819061,0.0,1647.0,...,-0.368318,0.000005,0.004084,0.001226,6.812843e-04,26695,NaN,0.429402,"POLYGON ((517329 3823551, 517329 3823548, 5173...",2.0
36792,0.0,1461.0,195.017831,343.950828,0.0,1699.0,250.890045,435.528911,0.0,2142.0,...,-0.204291,0.000035,0.003891,0.001438,7.882519e-04,26854,NaN,0.338542,"POLYGON ((516084 3823467, 516084 3823464, 5160...",2.0
36793,1209.0,1402.0,1287.588608,33.818415,1472.0,1616.0,1529.968354,29.235279,1730.0,1935.0,...,-0.708677,0.000138,0.003361,0.001373,6.631413e-04,26885,NaN,0.175844,"POLYGON ((516591 3823434, 516591 3823410, 5165...",2.0
36794,814.0,1158.0,932.567568,93.097026,1053.0,1366.0,1177.513514,94.159905,1261.0,1697.0,...,0.171085,0.000081,0.002542,0.001335,6.534902e-04,26910,NaN,0.274938,"POLYGON ((516495 3823404, 516495 3823401, 5164...",2.0
36795,659.0,1003.0,836.833333,53.407125,814.0,1259.0,1066.223368,53.252607,944.0,1575.0,...,1.312419,0.000049,0.004324,0.001452,7.984391e-04,26706,NaN,0.291831,"POLYGON ((517521 3823554, 517521 3823551, 5175...",2.0
36796,1204.0,1204.0,1204.000000,0.000000,1452.0,1452.0,1452.000000,0.000000,1687.0,1687.0,...,0.785398,0.001791,0.001791,0.001791,0.000000e+00,26915,NaN,0.255188,"POLYGON ((516510 3823389, 516510 3823386, 5165...",2.0
36797,984.0,1376.0,1144.042857,92.246322,1231.0,1634.0,1388.685714,96.501450,1464.0,2048.0,...,0.525878,0.000079,0.003412,0.001381,7.412638e-04,26903,NaN,0.236239,"POLYGON ((516507 3823413, 516507 3823410, 5165...",2.0
36798,1282.0,1453.0,1347.901639,35.534193,1561.0,1730.0,1625.081967,37.866156,1884.0,2180.0,...,0.145190,0.000094,0.002903,0.001474,6.374421e-04,26916,NaN,0.202989,"POLYGON ((516531 3823398, 516531 3823392, 5165...",3.0
36799,1117.0,1419.0,1245.955056,68.133529,1395.0,1705.0,1515.786517,79.911534,1731.0,2148.0,...,1.167805,0.000271,0.002755,0.001261,5.196733e-04,26900,NaN,0.189358,"POLYGON ((516561 3823425, 516561 3823422, 5165...",3.0
36800,0.0,1274.0,373.324461,455.137399,0.0,1495.0,475.223067,576.771350,0.0,1804.0,...,1.331593,0.000027,0.005197,0.001591,9.205362e-04,25896,NaN,0.281338,"POLYGON ((517626 3823764, 517626 3823752, 5176...",2.0
36801,0.0,1552.0,1.712042,40.834082,0.0,1839.0,2.179134,51.806896,0.0,2367.0,...,1.095076,0.000000,0.018006,0.001011,8.058398e-04,26688,NaN,0.261935,"POLYGON ((521448 3830424, 521448 3830406, 5214...",3.0
36802,0.0,1465.0,1137.597938,487.652628,0.0,1717.0,1372.958763,588.135354,0.0,2199.0,...,0.065029,0.000326,0.003970,0.001660,8.268797e-04,26917,NaN,0.191823,"POLYGON ((516597 3823386, 516597 3823383, 5165...",2.0
36803,1215.0,1406.0,1311.653061,40.608535,1502.0,1633.0,1571.311224,31.406974,1787.0,1993.0,...,-0.089838,0.000171,0.003474,0.001531,6.238472e-04,26906,NaN,0.188571,"POLYGON ((516594 3823410, 516594 3823404, 5165...",3.0

In [45]:
for_training.to_file("chev2_output.gpkg", layer = "predictions", driver = "GPKG")